version: '3.7'
services:
  redpanda:
    image: docker.redpanda.com/vectorized/redpanda:v21.11.8
    container_name: redpanda
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    - --pandaproxy-addr
    - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
    - --advertise-pandaproxy-addr
    - PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
    ports:
    - 8081:8081
    - 8082:8082
    - 9092:9092
    - 28082:28082
    - 29092:29092
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: elasticsearch
    restart: always
    environment:
      - node.name=es01
      - cluster.name=es-docker
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    healthcheck:
      test: curl -s -f elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 10

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.6
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy

  quarkus-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: kpalmab/quarkus-elasticsearch-kafka:native
    restart: always
    ports:
      - 8080:8080
    environment:
      - mp.messaging.outgoing.update-out.bootstrap.servers=redpanda:29092
      - mp.messaging.incoming.update-in.bootstrap.servers=redpanda:29092
      - mp.messaging.outgoing.child-out.bootstrap.servers=redpanda:29092
      - mp.messaging.incoming.child-in.bootstrap.servers=redpanda:29092
      - mp.messaging.outgoing.parent-out.bootstrap.servers=redpanda:29092
      - mp.messaging.incoming.parent-in.bootstrap.servers=redpanda:29092
      - kafka.bootstrap.servers=redpanda:29092
      - quarkus.elasticsearch.hosts=elasticsearch:9200
    depends_on:
      redpanda:
        condition: service_started
      elasticsearch:
        condition: service_healthy

volumes:
  data01:
    driver: local